### ISSUE TITLE
Micronaut Nats works with nats-streaming

### ISSUE THREAD

**Issue by alissonof** [micronaut-projects/micronaut-nats#128]
Hi people I'm planing to use nats with micronaut, but in my case I'm going to use nats-streaming. So. I would like to know if the micronaut nats works with nats-streaming. In positive case, please could send me an exemple.
Thank you

**Comment by fooock** [comment]
how can I help you with this? I need to be able to configure consumer ACK policy ([documentation here](https://docs.nats.io/nats-concepts/jetstream/consumers#ackpolicy)). I saw that there is a WIP PR #254

**Comment by grimmjo** [comment]
Hi @fooock,

thanks your reaching out 😃.
All the consumer configurations shown in the documentation can be configured via the `@ConsumerConfiguration` annotation.
I'm currently not sure, how we should differentiate pull and push consumers.
Pull consumer are always working with AckExplicit. I think one solution could be using a binder to explicitly bind the Ack handling to consumer method. 

You can try to implement this one as there are already other binder examples from nats-core in this repo.

**Comment by grimmjo** [comment]
Hey @fooock,

this is available in the current 4.0.0-SNAPSHOT version. The snapshots already target Micronaut 4.

Can you give it a try and leave a feedback her, so I can close this issue.

**Comment by grimmjo** [comment]
Closing this issue as Jetstream is implemented
