### ISSUE TITLE
Broken link to examples in README

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-nats#19]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Go to https://github.com/micronaut-projects/micronaut-nats/
2. Click on link "[examples](https://github.com/micronaut-projects/micronaut-nats/tree/master/examples)" in the README.md

### Expected Behaviour

It should go to the examples folder

### Actual Behaviour

The link is broken and the users cannot access the examples

### Environment Information

N/A

### Example Application

N/A

**Comment by grimmjo** [comment]
At the moment there are no examples, so I removed the link.
