### ISSUE TITLE
Migrate to new configuration ascidoc macro

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-nats#291]
### Issue description

Migrate to new configuration ascidoc macro

**Comment by grimmjo** [comment]
Hi @wetted,

I've migrated already migrated all the configurations :wink:

**Comment by wetted** [comment]
@grimmjo yes, I see those changes on master (for Micronaut 4. Thank you for contributing. I need them on the branch for Micronaut 3 as well, so I will merge the changes I need.
