### ISSUE TITLE
Subscribe to dynamic subject

### ISSUE THREAD

**Issue by Solido** [micronaut-projects/micronaut-nats#33]
We can subscribe to known subjects using a combinaison of annotations 
`@NatsListener & @Subject("MySub")`

But how to subscribe to

```
@NatsClient
interface DSync {
    void send(@Subject String **channel**, @Body String name)
}
```

Channel can't be specified in a annotation since it's a parameter ?
Should we use the default NATS java lib or does micronaut offer a solution ?

Much appreciated !

**Comment by grimmjo** [comment]
Hi @Solido, 

I don't understand your question exactly? So do you have a problem sending or receiving message? As your second code snippet shows, it looks like a sending issue.
This example might help you:

```java
import io.micronaut.nats.annotation.NatsClient;
import io.micronaut.nats.annotation.Subject;
import io.micronaut.messaging.annotation.Body;

@NatsClient 
public interface DSync {

    @Subject("my-subject") 
    void send(@Body String name);

    void sendProduct(@Subject String channel, @Body String name); 
}
```
I hope it helps. Otherwise just leave the question here

**Comment by grimmjo** [comment]
Hi @Solido, 

I don't understand your question exactly? So do you have a problem sending or receiving message? As your second code snippet shows, it looks like a sending issue.
This example might help you:

```java
import io.micronaut.nats.annotation.NatsClient;
import io.micronaut.nats.annotation.Subject;
import io.micronaut.messaging.annotation.Body;

@NatsClient 
public interface DSync {

    @Subject("my-subject") 
    void send(@Body String name);

    void sendProduct(@Subject String channel, @Body String name); 
}
```
I hope it helps. Otherwise just leave the question here

**Comment by grimmjo** [comment]
Could you tell me a little bit more about your use-case? Where do you get the list of subjects from?

**Comment by Solido** [comment]
Hi @grimmjo 

Thanks for the quick response.

Clarification : I send a message to a dynamic channel based on a parameter.
I don't know the name of the channel at compilation time so I can't use annotation.

**Comment by grimmjo** [comment]
There is no solution in micronaut-nats for creating dynamic listener during runtime. You can try implementing the listener yourself by using the existing nats connection. 
Another solution would be to use the beanContext and create a new bean. Maybe @graemerocher or @alvarosanchez have an idea, if something similiar is already possible in micronaut-rabbitmq or micronaut-kafka?

**Comment by Solido** [comment]
Hey can you provide some exemple on how to do that ?
I've been using Micronaut for a long time and this plugin is very confusing.

Release is 1.0.0 (production readay) but even the simple use cases are troublesome compared to using the original NATS API with default micronaut annotation.

Just a little doc would help a lot, I'm not able to find smth navigating the official API doc.

Also why is the doc talking about RabbitMQ or Kafka ?
https://micronaut-projects.github.io/micronaut-nats/latest/api/index.html

Thanks !

**Comment by grimmjo** [comment]
Do you already had a look at these docs?
https://micronaut-projects.github.io/micronaut-nats/latest/guide/

I will provide some examples soon and also show some nats specific features in doc..

**Comment by Solido** [comment]
Hi @grimmjo 

Thanks for you work on the plugin.

I've read the doc many time and I'll wait for your next update.
