### ISSUE TITLE
Nats bundle inside Micronaut ?

### ISSUE THREAD

**Issue by Solido** [micronaut-projects/micronaut-nats#34]
Hi !

Currently testing NATS inside Micronaut, so far so good.

Current process involve starting NATS outside and then bind Beans but it imply some more works when CI/CD or fast local dev.

What's the team position on bundling NATS binary with the plugin and starting / stopping the process ?

If it doesn't align with the framework philosophy what would be the best way to implement it myself ?

Currently I'm using startup event listener but server is starting after compiled classes open connection so it fails.

Thank you

**Comment by graemerocher** [comment]
Seems like it would be better to use something like test containers imo
